using UnityEngine;

[ExecuteInEditMode]
public class PlaneC : MonoBehaviour
{
    public Transform planeTransform; // El plano que define la posici贸n y rotaci贸n del corte
    public Material sliceMaterial; // El material con el shader de corte

    void Update()
    {
        if (planeTransform != null && sliceMaterial != null)
        {
            // Pasar la posici贸n del plano al shader
            sliceMaterial.SetVector("_PlanePosition", planeTransform.position);
            
            // Pasar la normal del plano (orientaci贸n) al shader
            sliceMaterial.SetVector("_PlaneNormal", planeTransform.up);
        }
    }
}
